name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Snake Animation
      - name: Generate Snake Animation
        id: snake-gif
        run: |
          echo "Generating Snake Animation..."
          docker run -it --rm -v "${PWD}:/mnt" ghcr.io/platane/github-contribution-grid-snake:latest --config /mnt/.github/workflows/snk-config.json --input /mnt/.github/workflows/snk-input.svg --output /mnt/dist/github-contribution-grid-snake.svg
        env:
          GITHUB_USER_NAME: GuiSousa2910
          GITHUB_TOKEN: ${{ secrets.snake }} # Use o nome do seu segredo aqui

      - name: Commit and Push SVG
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Add snake game contribution grid"
          git push
