name: Generate Datas

on:
  schedule:
    - cron: "*/5 * * * *" # Agendado a cada 5 minutos (intervalo máximo permitido)

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Check time interval
        id: check-time
        run: |
          current_hour=$(date +'%H')
          if [ $((current_hour % 12)) -eq 0 ]; then
            echo "Within the 12-hour interval. Performing the action."
          else
            echo "Outside the 12-hour interval. Skipping the action."
            exit 0
          fi

      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: GuiSousa2910
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
